# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
